version : '8'
services:
  auth:
    container_name: Auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    ports :
      - '4000:4000'
  books:
    container_name: Books
    build:
      context: .
      dockerfile: ./apps/books/Dockerfile
      target: development
    command: pnpm run start:dev books
    ports :
      - '8000:8000'
    env_file :
      - ./apps/books/.env
  cart:
    container_name: Cart
    build:
      context: .
      dockerfile: ./apps/cart/Dockerfile
      target: development
    command: pnpm run start:dev cart
    ports :
      - '5000:5000'
    env_file :
      - ./apps/cart/.env

  http-gateway:
    container_name: Http-Gateway
    build:
      context: .
      dockerfile: ./apps/http-gateway/Dockerfile
      target: development
    command: pnpm run start:dev http-gateway
    env_file :
      - ./apps/http-gateway/.env
    ports :
      - '3000:3000'

  momgodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "./db/data/db-files:/data/db"
  rabbitmq:
    hostname : rabbitmq
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
        - 5672:5672
        - 15672:15672
  redis:
    container_name: redis
    image: redis:7.0-rc1-alpine3.15
    restart: always
    ports:
      - 6379:6379

volumes:
  mongodb:



